/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t 
Author: MMSkecthfab (https://sketchfab.com/MMDSKETCH)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/yyb-42e65e775d6646db8ab45c7fc28588a0
Title: 《初音ミク》ＹＹＢタイプ
*/

import * as THREE from "three";

import React, { JSX } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_830: THREE.SkinnedMesh;
		Object_831: THREE.SkinnedMesh;
		Object_832: THREE.SkinnedMesh;
		Object_833: THREE.SkinnedMesh;
		Object_834: THREE.SkinnedMesh;
		Object_835: THREE.SkinnedMesh;
		Object_836: THREE.SkinnedMesh;
		Object_837: THREE.SkinnedMesh;
		Object_838: THREE.SkinnedMesh;
		Object_839: THREE.SkinnedMesh;
		Object_840: THREE.SkinnedMesh;
		Object_841: THREE.SkinnedMesh;
		Object_842: THREE.SkinnedMesh;
		Object_843: THREE.SkinnedMesh;
		Object_844: THREE.SkinnedMesh;
		Object_845: THREE.SkinnedMesh;
		Object_846: THREE.SkinnedMesh;
		Object_847: THREE.SkinnedMesh;
		Object_848: THREE.SkinnedMesh;
		Object_849: THREE.SkinnedMesh;
		Object_850: THREE.SkinnedMesh;
		Object_851: THREE.SkinnedMesh;
		Object_852: THREE.SkinnedMesh;
		Object_853: THREE.SkinnedMesh;
		Object_854: THREE.SkinnedMesh;
		Object_855: THREE.SkinnedMesh;
		Object_856: THREE.SkinnedMesh;
		Object_857: THREE.SkinnedMesh;
		Object_858: THREE.SkinnedMesh;
		Object_859: THREE.SkinnedMesh;
		Object_860: THREE.SkinnedMesh;
		Object_861: THREE.SkinnedMesh;
		Object_862: THREE.SkinnedMesh;
		Object_863: THREE.SkinnedMesh;
		Object_864: THREE.SkinnedMesh;
		Object_865: THREE.SkinnedMesh;
		Object_866: THREE.SkinnedMesh;
		Object_867: THREE.SkinnedMesh;
		Object_868: THREE.SkinnedMesh;
		Object_869: THREE.SkinnedMesh;
		Object_870: THREE.SkinnedMesh;
		Object_871: THREE.SkinnedMesh;
		Object_872: THREE.SkinnedMesh;
		Object_873: THREE.SkinnedMesh;
		Object_874: THREE.SkinnedMesh;
		Object_875: THREE.SkinnedMesh;
		Object_876: THREE.SkinnedMesh;
		Object_877: THREE.SkinnedMesh;
		Object_878: THREE.SkinnedMesh;
		Object_879: THREE.SkinnedMesh;
		Object_880: THREE.SkinnedMesh;
		Object_881: THREE.SkinnedMesh;
		Object_882: THREE.SkinnedMesh;
		Object_883: THREE.SkinnedMesh;
		_rootJoint: THREE.Bone;
	};
	materials: {
		body01: THREE.MeshBasicMaterial;
		material: THREE.MeshBasicMaterial;
		body02: THREE.MeshBasicMaterial;
		pantsu: THREE.MeshBasicMaterial;
		nail: THREE.MeshBasicMaterial;
		face01: THREE.MeshBasicMaterial;
		eyes: THREE.MeshBasicMaterial;
		eyes_7: THREE.MeshBasicMaterial;
		material_8: THREE.MeshBasicMaterial;
		face02: THREE.MeshBasicMaterial;
		face03: THREE.MeshBasicMaterial;
		face00: THREE.MeshBasicMaterial;
		face04: THREE.MeshBasicMaterial;
		face: THREE.MeshBasicMaterial;
		face05: THREE.MeshBasicMaterial;
		face06: THREE.MeshBasicMaterial;
		material_16: THREE.MeshBasicMaterial;
		hair03: THREE.MeshBasicMaterial;
		hair01: THREE.MeshBasicMaterial;
		hair02: THREE.MeshBasicMaterial;
		hair03_20: THREE.MeshBasicMaterial;
		hair01_21: THREE.MeshBasicMaterial;
		hair02_22: THREE.MeshBasicMaterial;
		glasses: THREE.MeshBasicMaterial;
		glasses02: THREE.MeshBasicMaterial;
		glasses02_25: THREE.MeshBasicMaterial;
		hairshadow: THREE.MeshBasicMaterial;
		headphone: THREE.MeshBasicMaterial;
		["headphone-L"]: THREE.MeshBasicMaterial;
		sleeve01: THREE.MeshBasicMaterial;
		sleeve02: THREE.MeshBasicMaterial;
		["sleeve-L"]: THREE.MeshBasicMaterial;
		sleeve03: THREE.MeshBasicMaterial;
		skirt01: THREE.MeshBasicMaterial;
		skirt01_34: THREE.MeshBasicMaterial;
		skirt02: THREE.MeshBasicMaterial;
		skirt02_36: THREE.MeshBasicMaterial;
		skirt03: THREE.MeshBasicMaterial;
		skirt03_38: THREE.MeshBasicMaterial;
		["skirt-L"]: THREE.MeshBasicMaterial;
		Boots01: THREE.MeshBasicMaterial;
		["Boots-L"]: THREE.MeshBasicMaterial;
		Boots02: THREE.MeshBasicMaterial;
		Boots03: THREE.MeshBasicMaterial;
		necktie01: THREE.MeshBasicMaterial;
		necktie: THREE.MeshBasicMaterial;
		clothes01: THREE.MeshBasicMaterial;
		clothes01_47: THREE.MeshBasicMaterial;
		clothes02: THREE.MeshBasicMaterial;
		clothes03: THREE.MeshBasicMaterial;
		clothes04: THREE.MeshBasicMaterial;
		["clothes-L"]: THREE.MeshBasicMaterial;
		OH_Outline_Material: THREE.MeshBasicMaterial;
	};
	// animations: GLTFAction[]
	animations: any[];
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
	const { scene } = useGLTF("/Waifu1.gltf");
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group scale={0.01}>
				<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
					<primitive object={nodes._rootJoint} />
					<skinnedMesh
						geometry={nodes.Object_830.geometry}
						material={materials.body01}
						skeleton={nodes.Object_830.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_831.geometry}
						material={materials.material}
						skeleton={nodes.Object_831.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_832.geometry}
						material={materials.body02}
						skeleton={nodes.Object_832.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_833.geometry}
						material={materials.pantsu}
						skeleton={nodes.Object_833.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_834.geometry}
						material={materials.nail}
						skeleton={nodes.Object_834.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_835.geometry}
						material={materials.face01}
						skeleton={nodes.Object_835.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_836.geometry}
						material={materials.eyes}
						skeleton={nodes.Object_836.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_837.geometry}
						material={materials.eyes_7}
						skeleton={nodes.Object_837.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_838.geometry}
						material={materials.material_8}
						skeleton={nodes.Object_838.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_839.geometry}
						material={materials.face02}
						skeleton={nodes.Object_839.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_840.geometry}
						material={materials.face03}
						skeleton={nodes.Object_840.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_841.geometry}
						material={materials.face00}
						skeleton={nodes.Object_841.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_842.geometry}
						material={materials.face04}
						skeleton={nodes.Object_842.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_843.geometry}
						material={materials.face}
						skeleton={nodes.Object_843.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_844.geometry}
						material={materials.face05}
						skeleton={nodes.Object_844.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_845.geometry}
						material={materials.face06}
						skeleton={nodes.Object_845.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_846.geometry}
						material={materials.material_16}
						skeleton={nodes.Object_846.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_847.geometry}
						material={materials.hair03}
						skeleton={nodes.Object_847.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_848.geometry}
						material={materials.hair01}
						skeleton={nodes.Object_848.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_849.geometry}
						material={materials.hair02}
						skeleton={nodes.Object_849.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_850.geometry}
						material={materials.hair03_20}
						skeleton={nodes.Object_850.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_851.geometry}
						material={materials.hair01_21}
						skeleton={nodes.Object_851.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_852.geometry}
						material={materials.hair02_22}
						skeleton={nodes.Object_852.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_853.geometry}
						material={materials.glasses}
						skeleton={nodes.Object_853.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_854.geometry}
						material={materials.glasses02}
						skeleton={nodes.Object_854.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_855.geometry}
						material={materials.glasses02_25}
						skeleton={nodes.Object_855.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_856.geometry}
						material={materials.hairshadow}
						skeleton={nodes.Object_856.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_857.geometry}
						material={materials.headphone}
						skeleton={nodes.Object_857.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_858.geometry}
						material={materials["headphone-L"]}
						skeleton={nodes.Object_858.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_859.geometry}
						material={materials.sleeve01}
						skeleton={nodes.Object_859.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_860.geometry}
						material={materials.sleeve02}
						skeleton={nodes.Object_860.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_861.geometry}
						material={materials["sleeve-L"]}
						skeleton={nodes.Object_861.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_862.geometry}
						material={materials.sleeve03}
						skeleton={nodes.Object_862.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_863.geometry}
						material={materials.skirt01}
						skeleton={nodes.Object_863.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_864.geometry}
						material={materials.skirt01_34}
						skeleton={nodes.Object_864.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_865.geometry}
						material={materials.skirt02}
						skeleton={nodes.Object_865.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_866.geometry}
						material={materials.skirt02_36}
						skeleton={nodes.Object_866.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_867.geometry}
						material={materials.skirt03}
						skeleton={nodes.Object_867.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_868.geometry}
						material={materials.skirt03_38}
						skeleton={nodes.Object_868.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_869.geometry}
						material={materials["skirt-L"]}
						skeleton={nodes.Object_869.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_870.geometry}
						material={materials.Boots01}
						skeleton={nodes.Object_870.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_871.geometry}
						material={materials["Boots-L"]}
						skeleton={nodes.Object_871.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_872.geometry}
						material={materials.Boots02}
						skeleton={nodes.Object_872.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_873.geometry}
						material={materials.Boots03}
						skeleton={nodes.Object_873.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_874.geometry}
						material={materials.necktie01}
						skeleton={nodes.Object_874.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_875.geometry}
						material={materials.necktie}
						skeleton={nodes.Object_875.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_876.geometry}
						material={materials.clothes01}
						skeleton={nodes.Object_876.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_877.geometry}
						material={materials.clothes01_47}
						skeleton={nodes.Object_877.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_878.geometry}
						material={materials.clothes02}
						skeleton={nodes.Object_878.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_879.geometry}
						material={materials.clothes03}
						skeleton={nodes.Object_879.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_880.geometry}
						material={materials.clothes04}
						skeleton={nodes.Object_880.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_881.geometry}
						material={materials["clothes-L"]}
						skeleton={nodes.Object_881.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_882.geometry}
						material={materials.OH_Outline_Material}
						skeleton={nodes.Object_882.skeleton}
					/>
					<skinnedMesh
						geometry={nodes.Object_883.geometry}
						material={materials.OH_Outline_Material}
						skeleton={nodes.Object_883.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/Waifu1.gltf");
